FROM microsoft/dotnet:2.0-sdk

# Install dependencies:
RUN apt-get update && apt-get install -y \
    libleveldb-dev \
    sqlite3 \
    libsqlite3-dev \
    libunwind8-dev \
    wget \
    zip

# APT cleanup to reduce image size
RUN rm -rf /var/lib/apt/lists/*
